language: haxe

haxe:
#  - 3.4.7
  - stable
#  - development

matrix:
  allow_failures:
    - haxe: development

addons:
#  chrome: stable
  firefox: "latest"

env:
  - MOZ_HEADLESS=1

install:
  - haxelib dev json5mod $(pwd)
#NOTE:hamcrest v.2,0,1 won't build with haxe: development
  - haxelib install hamcrest
  - haxelib install munit
#  - haxelib git hamcrest https://github.com/mikestead/hamcrest-haxe.git
#  - haxelib git munit https://github.com/massiveinteractive/MassiveUnit.git
  - haxelib install hxcpp
  - haxelib install hxjava
#  - haxelib install hxcs
#  - haxelib install hxnodejs

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - cd $TRAVIS_BUILD_DIR/test
  - echo $(node --version)

script:
#  - haxelib run munit test -js -browser phantomjs
  - haxelib run munit test -js -browser firefox -kill-browser
#  - haxelib run munit test -js -browser "google-chrome-stable --headless --no-sandbox --disable-gpu" -kill-browser
  - haxelib run munit test -neko
#  - haxelib run munit test -java
#  - haxelib run munit test -cpp

cache:
  directories:
    - $HOME/haxe/lib