language: haxe

haxe:
  - 3.4.7
  - stable
  - development

matrix:
  allow_failures:
    - haxe: development

install:
  - haxelib dev json5mod $(pwd)
  - haxelib install munit
  - haxelib install hamcrest
#  - haxelib install hxcpp

before_script:
  - cd $TRAVIS_BUILD_DIR/test

script:
  - haxelib run munit test -js
#  - haxelib run munit test -cpp
#  - haxelib run munit test -java
